"""Local-filesystem storage client for Chainlit's data layer.

Chainlit's SQLAlchemyDataLayer needs a `storage_provider` to persist ELEMENTS
(images, PDFs, files). Without one, `create_element` early-returns and elements
never reach the DB — so they vanish on reload (that's the startup warning
"storage client is not initialized and elements will not be persisted"). Chainlit
ships S3 / GCS / Azure clients but none for the local filesystem.

This minimal client writes element blobs under DATA_DIR/.cl_elements/<object_key>
(DATA_DIR is the bind mount → blobs survive container rebuilds) and returns
/cl-elements/<object_key> URLs. chat_app mounts a FastAPI route at that prefix to
serve them back (same origin as Chainlit → no CORS). Used so display_doc's PDF /
image elements reload after a refresh.

`object_key` is generated by Chainlit as "<user_id>/<element_id>" (contains a
slash), so upload_file makes parent dirs and the serving route uses a {:path}
matcher.
"""

import os
from typing import Any, Dict, Union

import aiofiles

from chainlit.data.storage_clients.base import BaseStorageClient

from sandbox_agent.config import DATA_DIR

ELEMENTS_DIR = os.path.join(DATA_DIR, ".cl_elements")
URL_PREFIX = "/cl-elements"


def resolve_object_path(object_key: str) -> str:
    """Resolve an object_key to an absolute path under ELEMENTS_DIR, rejecting
    traversal. Shared with chat_app's serving route."""
    base = os.path.realpath(ELEMENTS_DIR)
    full = os.path.realpath(os.path.join(base, object_key))
    if full != base and not full.startswith(base + os.sep):
        raise ValueError(f"object_key escapes elements dir: {object_key!r}")
    return full


class LocalFsStorageClient(BaseStorageClient):
    async def upload_file(
        self,
        object_key: str,
        data: Union[bytes, str],
        mime: str = "application/octet-stream",
        overwrite: bool = True,
        content_disposition: "str | None" = None,
    ) -> Dict[str, Any]:
        dest = resolve_object_path(object_key)
        os.makedirs(os.path.dirname(dest), exist_ok=True)
        if isinstance(data, str):
            data = data.encode()
        async with aiofiles.open(dest, "wb") as f:
            await f.write(data)
        return {"object_key": object_key, "url": f"{URL_PREFIX}/{object_key}"}

    async def delete_file(self, object_key: str) -> bool:
        try:
            os.unlink(resolve_object_path(object_key))
            return True
        except (OSError, ValueError):
            return False

    async def get_read_url(self, object_key: str) -> str:
        return f"{URL_PREFIX}/{object_key}"

    async def close(self) -> None:
        return None
